### PR TITLE
The possibility to specify a path to the settings file

### PR DESCRIPTION
**Pull request by kudashevs**
This is a continuation of the #41. This modified solution is reworked by taking into account suggestions and some new ideas:
-	Maybe we can rename this to `CONFIG_FILE_NAME` to keep it in line with the ConfigManager, etc...
Because I haven’t received any feedback on my explanations in #41 about my decision, I would like to stick to this naming for now. 
-	For most OSS package we avoid private for all properties and functions
I changed the visibility for all the methods which look worth being inherited. 
-	Explicitly importing `Throwable` is more in line with Laravel's codebase
Done for all the cases.
-	`createSource` might be a bit vague. Maybe we can rename it to something a bit more explicit?
The interface of the `ConfigManager` was change to:
```
  - load() 
  - save()
  - createPersistent() // can be safely removed if it seems a good idea not to expose it << was removed
  - getPersistentInfo()
```
, that looks better to me and more self-explantory
-	Also, what do you think about calling this method from the save() method?
Done. The `FileConfigManager` uses a new flow. It creates a file at the initialization moment (`createFile()`) and retains two states ($path, $file) for the future use. ~~That way it is not still necessary to create a persistent storage somewhere else (that's why createPersistent() method could be removed from the public Interface if it seems a good idea).~~ The `createPersistent` was removed from the public interface.
-	Interesting approach!
The approach turned out a big failure when I had tried to update `laravel-ignition` with this package. So, the solution was rethought and modified. Now, it should work without any possible issues.
-	Can this call be moved to inside of the $manager->save() method?
Done. It was mentioned above.
-	I don't think these doc block typehints add a lot
Because I haven’t received any feedback I left them as is.

Besides these refinements, I have finished a branch with [the integration of these changes](https://github.com/spatie/laravel-ignition/compare/main...kudashevs:settings_test) to the `laravel-ignition`. I haven't made a PR yet, because the branch uses a non-standard composer.json (with the modified version of `spatie/ignition`). @AlexVanderbist @freekmurze Could you please give it a look?

As an afterthought, I would like to propose to extract the functionality based on user's home directory (everything under the initPathFromEnvironment() method) to another class. It's not really crucial, but it is obviously sort of my fault because it breask SRP. It seems these (use predefined filename vs use the dynamically retrieved user home directory) are two different responsibilities with different functionality (works per project vs works for all the projects). So, it is better to do in the future.

### CODE REVIEW

**Comment by kudashevs** [comment]
Hello again,

This is a small update to the PR. I don't plan to update it more until the review. This update was necessary because the file creation process was clumsy (under the hood it has used the createPersistent() method from the public interface that gave some unjustified complexity).

So, this PR removes the createPersistent() from the public interface (I didn't find out any reason how it could be used in the future or why it should be available for external use). This decision simplifies the file creation process. In addition, I did some refactoring to simplify the readability and understanding, and to hide the exceeding complexity.

I look forward to seeing a review. Thank you in advance :)

**Comment by AlexVanderbist** [comment]
Hi again, thanks for re-opening this!

Your latest `FileConfigManager` refactor looks good! Bit of feedback still from the previous PR:

- there are still a couple of `private` methods in `FileConfigManager`, can we change those to `protected`? 
- keeping `SETTINGS_FILE_NAME` is fine for me, I do like the distinction between Laravel's config files and Ignition's settings file
- keeping the doc blocks to make it clear that they're associative arrays is also fine for me

>The FileConfigManager uses a new flow. It creates a file at the initialization moment (`createFile()`)

If it all possible, I would like to avoid creating this file on initialization and only create it when the user explicitly presses that save button.

>As an afterthought, I would like to propose to extract the functionality based on user's home directory (everything under the initPathFromEnvironment() method) to another class.

I don't see this as super crucial either, but it would be nice to have! What would that look like? A `SettingsPathResolver` or something? Would it optionally resolve from IOC too, like the `ConfigManager`?

Finally, I had a quick scroll through the changes required for laravel-ignition. Could you already create the PR with a `[DRAFT]` prefix? That'll make it a bit easier to review/manage feedback. Don't worry about the `composer.json` changes :)

Thanks again for taking the time!

**Comment by kudashevs** [comment]
@AlexVanderbist Hi,

Nice to hear that the refactor looks good :)

-	there are still a couple of private methods in FileConfigManager, can we change those to protected?
Do you want me to make all the methods protected, without any exceptions? 

-	If it all possible, I would like to avoid creating this file on initialization and only create it when the user explicitly presses that save button.
Sure, I’ll do it.

-	I don't see this as super crucial either, but it would be nice to have! What would that look like? A SettingsPathResolver or something? Would it optionally resolve from IOC too, like the ConfigManager?
It might look like multiple implementations via a common interface, where the exact implementation is set through config. In our case it would look like a FileConfigManager and EnvironmentConfigManager through the ConfigManager abstraction. Then a client could set one of the realizations in the config file in `laravel-ignition`. As an example.

- Finally, I had a quick scroll through the changes required for laravel-ignition. Could you already create the PR with a [DRAFT] prefix? That'll make it a bit easier to review/manage feedback. Don't worry about the composer.json changes :) 
Done.

**Comment by kudashevs** [comment]
@AlexVanderbist Hi again,

I moved the file create functionality to the `save()` method. I also did a refactoring of the path initialization process (remove duplication and simplify code). All the methods are protected now :)

**Review by AlexVanderbist — APPROVED** [review]
LGTM!

**Comment by AlexVanderbist** [comment]
Hi, thanks for the changes! I'll merge, test and tag this one. Let's continue our discussion in https://github.com/spatie/laravel-ignition/pull/66 👌 

Thanks again for all the work you've put into this PR!

**Pull request merged**
